version: '3.8'

services:
  database:
    image: postgres:14.4-alpine
    restart: always
    env_file:
      - ./postgres/.env
    ports:
      - '5432:5432'

  frontend-admin-web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./frontend-admin:/code
      - ./frontend-admin/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - frontend-admin

  frontend-admin:
    build:
      context: ./frontend-admin/docker/php
    volumes:
      - ./frontend-admin:/code
